function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "task2"};
	this.sidHashMap["task2"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "task2:22"};
	this.sidHashMap["task2:22"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "task2:7"};
	this.sidHashMap["task2:7"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<S3>"] = {sid: "task2:11"};
	this.sidHashMap["task2:11"] = {rtwname: "<S3>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "task2:26"};
	this.sidHashMap["task2:26"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/Is Even"] = {sid: "task2:22"};
	this.sidHashMap["task2:22"] = {rtwname: "<Root>/Is Even"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "task2:25"};
	this.sidHashMap["task2:25"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<S1>/In1"] = {sid: "task2:23"};
	this.sidHashMap["task2:23"] = {rtwname: "<S1>/In1"};
	this.rtwnameHashMap["<S1>/Constant"] = {sid: "task2:3"};
	this.sidHashMap["task2:3"] = {rtwname: "<S1>/Constant"};
	this.rtwnameHashMap["<S1>/If"] = {sid: "task2:6"};
	this.sidHashMap["task2:6"] = {rtwname: "<S1>/If"};
	this.rtwnameHashMap["<S1>/If Action Subsystem"] = {sid: "task2:7"};
	this.sidHashMap["task2:7"] = {rtwname: "<S1>/If Action Subsystem"};
	this.rtwnameHashMap["<S1>/If Action Subsystem1"] = {sid: "task2:11"};
	this.sidHashMap["task2:11"] = {rtwname: "<S1>/If Action Subsystem1"};
	this.rtwnameHashMap["<S1>/Math Function"] = {sid: "task2:1"};
	this.sidHashMap["task2:1"] = {rtwname: "<S1>/Math Function"};
	this.rtwnameHashMap["<S1>/Merge"] = {sid: "task2:15"};
	this.sidHashMap["task2:15"] = {rtwname: "<S1>/Merge"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "task2:24"};
	this.sidHashMap["task2:24"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S2>/Action Port"] = {sid: "task2:9"};
	this.sidHashMap["task2:9"] = {rtwname: "<S2>/Action Port"};
	this.rtwnameHashMap["<S2>/String Constant"] = {sid: "task2:17"};
	this.sidHashMap["task2:17"] = {rtwname: "<S2>/String Constant"};
	this.rtwnameHashMap["<S2>/Out1"] = {sid: "task2:10"};
	this.sidHashMap["task2:10"] = {rtwname: "<S2>/Out1"};
	this.rtwnameHashMap["<S3>/Action Port"] = {sid: "task2:13"};
	this.sidHashMap["task2:13"] = {rtwname: "<S3>/Action Port"};
	this.rtwnameHashMap["<S3>/String Constant"] = {sid: "task2:16"};
	this.sidHashMap["task2:16"] = {rtwname: "<S3>/String Constant"};
	this.rtwnameHashMap["<S3>/Out1"] = {sid: "task2:14"};
	this.sidHashMap["task2:14"] = {rtwname: "<S3>/Out1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
